default: &default
  adapter: postgresql
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: wuji_karma_development
  pool: 5

test:
  <<: *default
  database: wuji_karma_test

production:
  <<: *default
  database: wuji_karma_production
