default: &default
  aws_s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>
  aws_s3_host_name: <%= ENV['AWS_S3_HOST_NAME'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  
  tierion_username: <%= ENV['TIERION_USERNAME'] %>
  tierion_password: <%= ENV['TIERION_PASSWORD'] %>

development:
  <<: *default
  secret_key_base: 1204ae447dc74614a6af93625c9a22fc2545f7e3fad8291c70d0ce87e8be86dbcff2f44825e5a0f375018a688414d4050b40b8b88d6ed49189e1d8ca39dca4fc

test:
  <<: *default
  secret_key_base: 457aa8d1bd54692279b6f4907be3476dd4f1dfc6767cf7bfb3b1faec16521b437ab9b3c4e7391ba210a9c8363217e33677ff7854bd877bd29faaf7fafeffaa2c

staging:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
